### ISSUE TITLE
Python error when clicking on book

### ISSUE THREAD

**Issue by johnmmcgee** [linuxserver/docker-calibre-web#61] opened 2020-02-11 02:49 UTC
When i attempt to click on a book, to open.  I am served with this screen:

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1471, in show_book
is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 347, in __getattr__
return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'

**Comment by CHBMB** [comment] 2020-02-11 09:54
@johnmmcgee I'm going to close this so you can reopen a new issue filling out the template, otherwise we have no way to even begin to try and reproduce an issue.  I use Calibre-web and am not seeing this behaviour.

I have seen odd issues specific to a certain book as well, and trying another book doesn't generate an error.

That being said I am aware of an issue with the latest container, so for the time being `0.6.5-ls47` is the tag to use, however I'm not seeing the error message you describe.

**Comment by CHBMB** [comment] 2020-02-11 09:57
OK, managed to reproduce it.

**Closed** 2020-02-11 12:06 UTC
Labels: bug

**Comment by IInvocation** [comment] 2020-02-11 20:25
Hi,
i'm actually still experiencing this problem. Ran into it using linuxserver/calibre-web image. Just to be sure - i'm now using linuxserver/calibre-web:latest explicitly which should fix the issue - right?

> The logfile still contains entries as the following when opening any book:
> [2020-02-11 20:19:15,338] ERROR {cps:1891} Exception on /book/51188 [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/app/calibre-web/cps/web.py", line 166, in decorated_view
>     return login_required(func)(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 272, in decorated_view
>     return func(*args, **kwargs)
>   File "/app/calibre-web/cps/web.py", line 1471, in show_book
>     is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
>   File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 347, in __getattr__
>     return getattr(self._get_current_object(), name)
> AttributeError: 'Request' object has no attribute 'is_xhr'

**Comment by rablador** [comment] 2020-02-13 22:43
Having the same problem too...

**Comment by CHBMB** [comment] 2020-02-24 10:03
@IInvocation Remove your container and docker image for Calibre-web and try pulling latest again.  If the issue is persistent open a new issue being sure to fill out the template as requested as I'm 100% sure this issue has been resolved.
