### ISSUE TITLE
[BUG] Very high IO wait on initial launch

### ISSUE THREAD

**Issue by mpatton125** [linuxserver/docker-calibre-web#257] opened 2023-06-01 03:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to the chown present when the image is initially launched, my system faces very high IO wait that impacts the rest of my system activities.

To put this in context I have a very large library with over 570000 books and more than 1 million files under /app/calibre-web/cps/cache (bind mount to the host for persistence).

Would it be possible to replace the global chown with a find that applies a chown only to files without the correct ownership already?

### Expected Behavior

Only files that were not owned by abc.abc should be chown'ed.

### Steps To Reproduce

1) Launch the container
2) Wait while the chown takes forever...

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:nightly
    restart: unless-stopped
    networks:
      docker_vlan:
    hostname: calibre-web
    container_name: calibre-web
    mac_address: 02:42:0a:00:02:21
    volumes:
      - type: bind
        source: /storage/docker/calibre-web/config/
        target: /config/
      - type: bind
        source: '/storage/Library'
        target: /books
      - type: bind
        source: /storage/docker/calibre-web/cache/
        target: /app/calibre-web/cps/cache/
    environment:
      - TZ=Australia/Sydney
      - PUID=1000
      - GUID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre
```

### Container logs

```bash
Not sure this is relevant.
```

**Comment by mpatton125** [comment] 2023-07-02 00:08
I modified /root/etc/s6-overlay/s6-rc.d/init-calibre-web-config/run as follows and it appears to work:
```
# permissions
#lsiown -R abc:abc \
#    /config \
#    /app/calibre-web/cps/cache

/usr/bin/find /config \( \! -group abc -o \! -user abc \) -exec chown abc:abc {} \;
/usr/bin/find /app/calibre-web/cps/cache \( \! -group abc -o \! -user abc \) -exec chown abc:abc {} \;
```

**Comment by mpatton125** [comment] 2023-08-05 06:39
Any chance my patch (above) is suitable?

**Comment by quietsy** [comment] 2023-09-18 15:10
@mpatton125 We pushed a fix for lsiown, can you please check if the problem is fixed now?

**Comment by mpatton125** [comment] 2023-09-19 03:14
@quietsy - I can confirm the fix works as expected for me.  No more huge spikes of IO wait.  Many thanks.

**Closed** 2023-09-19 04:32 UTC
