### ISSUE TITLE
no close button when you read EPUB book

### ISSUE THREAD

**Issue by schel4ok** [linuxserver/docker-calibre-web#109] opened 2020-12-06 20:03 UTC
When open EPUB book card it is possible to read directly in browser, but there is no close button when you read it.
I checked in Chrome browser on android mobile phone and in Chrome browser on laptop.

**Comment by CHBMB** [comment] 2020-12-09 18:11
Sounds like an upstream issue rather than a peculiarity of the docker container.

**Comment by schel4ok** [comment] 2020-12-09 18:15
you mean that it should be addressed to calibre developper?

**Comment by j0nnymoe** [comment] 2020-12-09 18:39
To the calibre-web developer, yea.

**Comment by CHBMB** [comment] 2021-01-14 18:56
Closing this as it's an upstream feature request not a bug.

**Closed by CHBMB** 2021-01-14 18:56 UTC
Labels: no-issue-activity
