### ISSUE TITLE
[BUG] Docker Mods for Calibre override my plugins config

### ISSUE THREAD

**Issue by momja** [linuxserver/docker-calibre-web#279] opened 2023-10-23 02:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the universal-calibre docker mod enabled, my calibre config directory gets rewritten _after_ the docker container is created. so, any plugins I have configured get erased, and the `customize.py.json`  file is also deleted.

I.E. when I first check `customize.py.json` immediately after bringing up my container:
```
#  cat ~/.config/calibre/customize.py.json 
{
  "disabled_plugins": {
    "__class__": "set",
    "__value__": []
  },
  "enabled_plugins": {
    "__class__": "set",
    "__value__": [
      "DeDRM_plugin"
    ]
  },
  "filetype_mapping": {},
  "plugin_customization": {},
  "plugins": {
    "DeDRM": "/root/.config/calibre/plugins/DeDRM.zip"
  }
}
```

Then, after waiting a minute:
```
# cat ~/.config/calibre/customize.py.json
cat: /root/.config/calibre/customize.py.json: No such file or directory
```

Maybe this is just how docker mods and calibre works, but my expectation would be that calibre preserves the plugins configured.

### Expected Behavior

I would expect it to preserve whatever config I already have set up

### Steps To Reproduce

1. Setup a docker compose file using docker mods
2. Reference a volume in the compose file that will be used for the calibre config directory `~/.config/calibre/` and setup some plugins
3. Bring up the container
4. Wait a few minutes
5. Try to utilize the plugin, and notice it is not installed or enabled, and the config files are removed.

### Environment

```markdown
- OS:
- How docker service was installed:

Ubuntu 22.04.1
Installed using the distro's default package manager
```

### CPU architecture

arm64

### Docker creation

```bash
Docker Compose:


---
version: "3"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional calibre layer support
    volumes:
      - ${BOOKS_NEXTCLOUD_DIR}:/books
      - ${BOOKS_NEXTCLOUD_DIR}_upload:/book_upload
      - ${CALIBRE_DATA_DIR}/plugins:/app/calibre/plugins
      - ${CALIBRE_DATA_DIR}/config
      - ${CALIBRE_DATA_DIR}/calibre-config:/root/.config/calibre
      - ${CALIBRE_DATA_DIR}/DeDRM_plugin.zip:/DeDRM_plugin.zip
      - ./scripts:/scripts
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - lan
    labels:
      - "traefik.enable=true"

      # Local Domain for OPDS feed
      - "traefik.http.routers.calibre-http-local.rule=Host(`calibre.lan`)"
      - "traefik.http.routers.calibre-http-local.entrypoints=web"

      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.calibre-http.rule=Host(`${CALIBRE_DOMAIN}`)"
      - "traefik.http.routers.calibre-http.entrypoints=web"
      - "traefik.http.routers.calibre-http.middlewares=redirect-https"

      - "traefik.http.routers.calibre.rule=Host(`${CALIBRE_DOMAIN}`)"
      - "traefik.http.routers.calibre.entrypoints=https"
      - "traefik.http.routers.calibre.tls=true"

networks:
    lan:
        external: true
```
```


### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-calibre to container
[mod-init] Downloading linuxserver/mods:universal-calibre from lscr.io
[mod-init] Installing linuxserver/mods:universal-calibre
[mod-init] linuxserver/mods:universal-calibre applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    33
User GID:    33
───────────────────────────────────────

**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports jammy/restricted Sources [28.2 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports jammy/main Sources [1,668 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse Sources [361 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports jammy/universe Sources [22.0 MB]
Get:8 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages [17.2 MB]
Get:9 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages [1,758 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports jammy/restricted arm64 Packages [24.2 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse arm64 Packages [224 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main Sources [553 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe Sources [358 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted Sources [58.8 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse Sources [21.0 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1,226 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [847 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [1,163 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [27.8 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse Sources [11.3 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports jammy-security/main Sources [283 kB]
Get:22 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe Sources [207 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted Sources [56.0 kB]
Get:24 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [840 kB]
Get:25 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [964 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse arm64 Packages [23.4 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [902 kB]
Fetched 51.3 MB in 7s (7,192 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxkbfile1 is already the newest version (1:1.1.0-1build3).
libxkbfile1 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxtst6 is already the newest version (2:1.2.3-1build4).
libnss3 is already the newest version (2:3.68.2-0ubuntu1.2).
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libelf1 libgbm1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm15 libsensors-config libsensors5
  libwayland-client0 libwayland-server0 libx11-xcb1 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-shm0
  libxcb-sync1 libxcb-xfixes0 libxfixes3 libxshmfence1 libxxf86vm1 xkb-data
Suggested packages:
  lm-sensors
Recommended packages:
  libgl1-amber-dri
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libegl1 libelf1 libgbm1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm15 libopengl0
  libsensors-config libsensors5 libwayland-client0 libwayland-server0
  libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-randr0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxdamage1 libxfixes3
  libxkbcommon0 libxshmfence1 libxxf86vm1 xkb-data xz-utils
0 upgraded, 39 newly installed, 0 to remove and 10 not upgraded.
Need to get 33.3 MB of archives.
After this operation, 147 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libelf1 arm64 0.186-1build1 [50.7 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 xkb-data all 2.33-1 [394 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libdrm-common all 2.4.113-2~ubuntu0.22.04.1 [5,450 B]
Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libdrm2 arm64 2.4.113-2~ubuntu0.22.04.1 [39.1 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libedit2 arm64 3.1-20210910-1build1 [96.0 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 xz-utils arm64 5.2.5-2ubuntu1 [84.4 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libdrm-amdgpu1 arm64 2.4.113-2~ubuntu0.22.04.1 [19.8 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libdrm-nouveau2 arm64 2.4.113-2~ubuntu0.22.04.1 [17.5 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libdrm-radeon1 arm64 2.4.113-2~ubuntu0.22.04.1 [21.2 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libwayland-server0 arm64 1.20.0-1ubuntu0.1 [34.1 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libgbm1 arm64 23.0.4-0ubuntu1~22.04.1 [33.3 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libglapi-mesa arm64 23.0.4-0ubuntu1~22.04.1 [55.5 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libwayland-client0 arm64 1.20.0-1ubuntu0.1 [25.4 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libx11-xcb1 arm64 2:1.7.5-1ubuntu0.3 [7,822 B]
Get:15 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-dri2-0 arm64 1.14-3ubuntu3 [7,242 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-dri3-0 arm64 1.14-3ubuntu3 [6,922 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-present0 arm64 1.14-3ubuntu3 [5,724 B]
Get:18 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-randr0 arm64 1.14-3ubuntu3 [18.4 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-sync1 arm64 1.14-3ubuntu3 [9,312 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-xfixes0 arm64 1.14-3ubuntu3 [10.0 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxshmfence1 arm64 1.3-1build4 [5,444 B]
Get:22 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libegl-mesa0 arm64 23.0.4-0ubuntu1~22.04.1 [115 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libllvm15 arm64 1:15.0.7-0ubuntu0.22.04.3 [24.2 MB]
Get:24 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libsensors-config all 1:3.6.0-7ubuntu1 [5,274 B]
Get:25 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libsensors5 arm64 1:3.6.0-7ubuntu1 [26.1 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libgl1-mesa-dri arm64 23.0.4-0ubuntu1~22.04.1 [7,392 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libglvnd0 arm64 1.4.0-1 [61.0 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-glx0 arm64 1.14-3ubuntu3 [26.1 kB]
Get:29 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxcb-shm0 arm64 1.14-3ubuntu3 [5,848 B]
Get:30 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxfixes3 arm64 1:6.0.0-1 [11.4 kB]
Get:31 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxxf86vm1 arm64 1:1.1.4-1build3 [10.3 kB]
Get:32 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 libglx-mesa0 arm64 23.0.4-0ubuntu1~22.04.1 [165 kB]
Get:33 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libglx0 arm64 1.4.0-1 [37.1 kB]
Get:34 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libgl1 arm64 1.4.0-1 [114 kB]
Get:35 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 libgl1-mesa-glx arm64 23.0.4-0ubuntu1~22.04.1 [5,584 B]
Get:36 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxdamage1 arm64 1:1.1.5-2build2 [6,950 B]
Get:37 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libxkbcommon0 arm64 1.4.0-1 [122 kB]
Get:38 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libegl1 arm64 1.4.0-1 [28.8 kB]
Get:39 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 libopengl0 arm64 1.4.0-1 [38.6 kB]
Fetched 33.3 MB in 6s (5,393 kB/s)
Selecting previously unselected package libelf1:arm64.
(Reading database ... 11650 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.186-1build1_arm64.deb ...
Unpacking libelf1:arm64 (0.186-1build1) ...
Selecting previously unselected package xkb-data.
Preparing to unpack .../01-xkb-data_2.33-1_all.deb ...
Unpacking xkb-data (2.33-1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.113-2~ubuntu0.22.04.1_all.deb ...
Unpacking libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm2:arm64.
Preparing to unpack .../03-libdrm2_2.4.113-2~ubuntu0.22.04.1_arm64.deb ...
Unpacking libdrm2:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libedit2:arm64.
Preparing to unpack .../04-libedit2_3.1-20210910-1build1_arm64.deb ...
Unpacking libedit2:arm64 (3.1-20210910-1build1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../05-xz-utils_5.2.5-2ubuntu1_arm64.deb ...
Unpacking xz-utils (5.2.5-2ubuntu1) ...
Selecting previously unselected package libdrm-amdgpu1:arm64.
Preparing to unpack .../06-libdrm-amdgpu1_2.4.113-2~ubuntu0.22.04.1_arm64.deb ...
Unpacking libdrm-amdgpu1:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-nouveau2:arm64.
Preparing to unpack .../07-libdrm-nouveau2_2.4.113-2~ubuntu0.22.04.1_arm64.deb ...
Unpacking libdrm-nouveau2:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libdrm-radeon1:arm64.
Preparing to unpack .../08-libdrm-radeon1_2.4.113-2~ubuntu0.22.04.1_arm64.deb ...
Unpacking libdrm-radeon1:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Selecting previously unselected package libwayland-server0:arm64.
Preparing to unpack .../09-libwayland-server0_1.20.0-1ubuntu0.1_arm64.deb ...
Unpacking libwayland-server0:arm64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libgbm1:arm64.
Preparing to unpack .../10-libgbm1_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libgbm1:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglapi-mesa:arm64.
Preparing to unpack .../11-libglapi-mesa_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libglapi-mesa:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libwayland-client0:arm64.
Preparing to unpack .../12-libwayland-client0_1.20.0-1ubuntu0.1_arm64.deb ...
Unpacking libwayland-client0:arm64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libx11-xcb1:arm64.
Preparing to unpack .../13-libx11-xcb1_2%3a1.7.5-1ubuntu0.3_arm64.deb ...
Unpacking libx11-xcb1:arm64 (2:1.7.5-1ubuntu0.3) ...
Selecting previously unselected package libxcb-dri2-0:arm64.
Preparing to unpack .../14-libxcb-dri2-0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-dri2-0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-dri3-0:arm64.
Preparing to unpack .../15-libxcb-dri3-0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-dri3-0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-present0:arm64.
Preparing to unpack .../16-libxcb-present0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-present0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-randr0:arm64.
Preparing to unpack .../17-libxcb-randr0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-randr0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-sync1:arm64.
Preparing to unpack .../18-libxcb-sync1_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-sync1:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xfixes0:arm64.
Preparing to unpack .../19-libxcb-xfixes0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-xfixes0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxshmfence1:arm64.
Preparing to unpack .../20-libxshmfence1_1.3-1build4_arm64.deb ...
Unpacking libxshmfence1:arm64 (1.3-1build4) ...
Selecting previously unselected package libegl-mesa0:arm64.
Preparing to unpack .../21-libegl-mesa0_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libegl-mesa0:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libllvm15:arm64.
Preparing to unpack .../22-libllvm15_1%3a15.0.7-0ubuntu0.22.04.3_arm64.deb ...
Unpacking libllvm15:arm64 (1:15.0.7-0ubuntu0.22.04.3) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../23-libsensors-config_1%3a3.6.0-7ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libsensors5:arm64.
Preparing to unpack .../24-libsensors5_1%3a3.6.0-7ubuntu1_arm64.deb ...
Unpacking libsensors5:arm64 (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libgl1-mesa-dri:arm64.
Preparing to unpack .../25-libgl1-mesa-dri_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libgl1-mesa-dri:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglvnd0:arm64.
Preparing to unpack .../26-libglvnd0_1.4.0-1_arm64.deb ...
Unpacking libglvnd0:arm64 (1.4.0-1) ...
Selecting previously unselected package libxcb-glx0:arm64.
Preparing to unpack .../27-libxcb-glx0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-glx0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-shm0:arm64.
Preparing to unpack .../28-libxcb-shm0_1.14-3ubuntu3_arm64.deb ...
Unpacking libxcb-shm0:arm64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxfixes3:arm64.
Preparing to unpack .../29-libxfixes3_1%3a6.0.0-1_arm64.deb ...
Unpacking libxfixes3:arm64 (1:6.0.0-1) ...
Selecting previously unselected package libxxf86vm1:arm64.
Preparing to unpack .../30-libxxf86vm1_1%3a1.1.4-1build3_arm64.deb ...
Unpacking libxxf86vm1:arm64 (1:1.1.4-1build3) ...
Selecting previously unselected package libglx-mesa0:arm64.
Preparing to unpack .../31-libglx-mesa0_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libglx-mesa0:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libglx0:arm64.
Preparing to unpack .../32-libglx0_1.4.0-1_arm64.deb ...
Unpacking libglx0:arm64 (1.4.0-1) ...
Selecting previously unselected package libgl1:arm64.
Preparing to unpack .../33-libgl1_1.4.0-1_arm64.deb ...
Unpacking libgl1:arm64 (1.4.0-1) ...
Selecting previously unselected package libgl1-mesa-glx:arm64.
Preparing to unpack .../34-libgl1-mesa-glx_23.0.4-0ubuntu1~22.04.1_arm64.deb ...
Unpacking libgl1-mesa-glx:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package libxdamage1:arm64.
Preparing to unpack .../35-libxdamage1_1%3a1.1.5-2build2_arm64.deb ...
Unpacking libxdamage1:arm64 (1:1.1.5-2build2) ...
Selecting previously unselected package libxkbcommon0:arm64.
Preparing to unpack .../36-libxkbcommon0_1.4.0-1_arm64.deb ...
Unpacking libxkbcommon0:arm64 (1.4.0-1) ...
Selecting previously unselected package libegl1:arm64.
Preparing to unpack .../37-libegl1_1.4.0-1_arm64.deb ...
Unpacking libegl1:arm64 (1.4.0-1) ...
Selecting previously unselected package libopengl0:arm64.
Preparing to unpack .../38-libopengl0_1.4.0-1_arm64.deb ...
Unpacking libopengl0:arm64 (1.4.0-1) ...
Setting up libxcb-dri3-0:arm64 (1.14-3ubuntu3) ...
Setting up libwayland-server0:arm64 (1.20.0-1ubuntu0.1) ...
Setting up libx11-xcb1:arm64 (2:1.7.5-1ubuntu0.3) ...
Setting up libxdamage1:arm64 (1:1.1.5-2build2) ...
Setting up libxcb-xfixes0:arm64 (1.14-3ubuntu3) ...
Setting up libglvnd0:arm64 (1.4.0-1) ...
Setting up libxcb-glx0:arm64 (1.14-3ubuntu3) ...
Setting up libedit2:arm64 (3.1-20210910-1build1) ...
Setting up libsensors-config (1:3.6.0-7ubuntu1) ...
Setting up xkb-data (2.33-1) ...
Setting up libxcb-shm0:arm64 (1.14-3ubuntu3) ...
Setting up libopengl0:arm64 (1.4.0-1) ...
Setting up libxxf86vm1:arm64 (1:1.1.4-1build3) ...
Setting up libxcb-present0:arm64 (1.14-3ubuntu3) ...
Setting up libxfixes3:arm64 (1:6.0.0-1) ...
Setting up libxcb-sync1:arm64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libsensors5:arm64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libxcb-dri2-0:arm64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:arm64 (1.3-1build4) ...
Setting up libxcb-randr0:arm64 (1.14-3ubuntu3) ...
Setting up libllvm15:arm64 (1:15.0.7-0ubuntu0.22.04.3) ...
Setting up libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libelf1:arm64 (0.186-1build1) ...
Setting up libxkbcommon0:arm64 (1.4.0-1) ...
Setting up libwayland-client0:arm64 (1.20.0-1ubuntu0.1) ...
Setting up libdrm2:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-amdgpu1:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-nouveau2:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgbm1:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libdrm-radeon1:arm64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgl1-mesa-dri:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl-mesa0:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libegl1:arm64 (1.4.0-1) ...
Setting up libglx-mesa0:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up libglx0:arm64 (1.4.0-1) ...
Setting up libgl1:arm64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:arm64 (23.0.4-0ubuntu1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
rm: cannot remove '/app/calibre/plugins': Device or resource busy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  120M  100  120M    0     0  67.3M      0  0:00:01  0:00:01 --:--:--  112M
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


	Traceback (most recent call last):
	 File "calibre/linux.py", line 858, in setup_desktop_integration
	 File "calibre/linux.py", line 880, in do_setup_desktop_integration
	 File "calibre/linux.py", line 911, in install_xdg_junk
	 File "calibre/linux.py", line 896, in install_icons
	 File "calibre/linux.py", line 890, in install_single_icon
	 File "subprocess.py", line 364, in check_call
	 File "subprocess.py", line 345, in call
	 File "subprocess.py", line 966, in __init__
	 File "subprocess.py", line 1842, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall


There were 1 warnings

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by adamshand** [comment] 2023-10-25 19:06
I just upgraded to latest and am also getting the "Setting up desktop integration failed with error" error on startup.

**Comment by momja** [comment] 2023-10-25 22:59
@adamshand I'm not certain that error in the log is what actually causes the issue I'm filing. Since this is running "headless" I don't know if that error is relevant to any issue.

**Comment by adamshand** [comment] 2023-10-25 23:37
I'm running headless as well.  

Removing "DOCKER_MODS=linuxserver/mods:universal-calibre" from my docker-compose.yml got rid of the error for me.

**Comment by momja** [comment] 2023-10-26 05:13
> I'm running headless as well.

Sorry, I wasn't clear. The issue that you are encountering I suspect is that somewhere the build of calibre used by the docker mod expects to have some desktop environment to plug into, which doesn't exist, causing this exception. I don't expect this actually causes issue since it's not really designed for using calibre as a desktop application anyway here. If you don't need the docker mod, happy that fixes the problem for you. My issue is that the mod is not working the way I'd expect it to. My workflow requires that I have calibre installed on my docker container since I'm relying on some of its plugins for aiding in ebook conversion.

**Comment by drizuid** [comment] 2023-10-28 19:49
> ### Current Behavior
> With the universal-calibre docker mod enabled, my calibre config directory gets rewritten _after_ the docker container is created. so, any plugins I have configured get erased, and the `customize.py.json` file is also deleted.
> 


if you are trying to leverage custom plugin configs, you should be following https://www.linuxserver.io/custom  are you doing so?

**Comment by pluim003** [comment] 2023-11-25 08:35
I have the same error by simply firing it up with the provided docker-compose.yaml with only volumes modified.

**Comment by drizuid** [comment] 2023-11-25 15:05
Provided the supported method to use custom scripts and such, OP did not reply for a full month. Closing as we cannot reproduce any issue.

**Closed by drizuid** 2023-11-25 15:05 UTC
