### ISSUE TITLE
[BUG] No such file or directory: 'xdg-icon-resource'

### ISSUE THREAD

**Issue by alfureu** [linuxserver/docker-calibre-web#243] opened 2023-04-09 06:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/10846169/230758452-b1b02500-98a6-498f-9e6b-024f32692132.png)

When I start the docker-compose up command....

### Expected Behavior

Should build without error

### Steps To Reproduce

1. follow the docker-compose file from the linuxserver page

### Environment

```markdown
- OS: linux
- How docker service was installed: n/a
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up
```

### Container logs

```bash
see above screenshot
```

**Comment by gmillerd** [comment] 2023-04-30 04:16
This is what the sample docker-compose yields, its just a loop of apt update, apt install, crash on xdg-icon-resource.

@alfureu Removing 'DOCKER_MODS: linuxserver/mods:universal-calibre' gets past this, fwiw

**Comment by hieronymousch** [comment] 2023-05-15 16:36
I have the same issue

**Comment by janosimas** [comment] 2023-05-21 10:02
Same for me.

@gmillerd Removing that, disables ebook conversion, I don't see that as a solution

**Comment by sveinbjornpalsson** [comment] 2023-05-23 17:05
same issue.

**Comment by aptalca** [comment] 2023-05-23 17:26
Posting `same issue`, especially on one that is marked `invalid` for not having enough info in the issue description is extremely unhelpful.

`No such file or directory: 'xdg-icon-resource'` is a harmless error shown in the logs. We are not aware of any actual issues it causes other than failing to complete desktop integration, which is not something needed in this container anyway.

Closing. If you are experiencing actual issues, please open a new github issue, describe the issue in detail and fill out the issue template fully.

**Closed by aptalca** 2023-05-23 17:26 UTC
Labels: invalid

**Comment by janosimas** [comment] 2023-05-23 19:56
> No such file or directory: 'xdg-icon-resource' is a harmless error shown in the logs. 

I had the same error and itself may be harmless but the service wouldn't start.

In my case, the issue was the `#optional` in `- DOCKER_MODS=linuxserver/mods:universal-calibre #optional`.

Removing it solved the issue, and all worked as intended.

**Comment by sveinbjornpalsson** [comment] 2023-05-24 14:50
I'd like to add that with a little help from our friend GPT, I figured this out.

I am installing on Synology DSM, which doesn't have the X-window graphical interface common to linux. These are bits that can't connect to that, and are not needed. 

If someone were super bored, you could write something in that would check for that and then ignore those bits, but as people smarter than me have said here, as it's not creating problems, there's nothing to solve.

But for those who want to know what this was, now you know.

**Comment by HernandoR** [comment] 2024-02-24 05:20
> > No such file or directory: 'xdg-icon-resource' is a harmless error shown in the logs.
> 
> I had the same error and itself may be harmless but the service wouldn't start.
> 
> In my case, the issue was the `#optional` in `- DOCKER_MODS=linuxserver/mods:universal-calibre #optional`.
> 
> Removing it solved the issue, and all worked as intended.

Same issue, removed `#optional` but issue remains

**Comment by sveinbjornpalsson** [comment] 2024-02-24 13:26
> Posting `same issue`, especially on one that is marked `invalid` for not having enough info in the issue description is extremely unhelpful.

I don't think people look at these logs unless something isn't working. Mostly.

The irony is that just marking it 'invalid' is also not enough info to go on. 

I may have missed the bit where you said it was a harmless bug first time around, since this wasn't the case for me. Or so I recall. It's been a year so I'm not sure.

If I remember correctly, I was having issues with calibre (and calibre-web), and when seeing this error, I drew the obvious conclusion that this was the problem I needed to solve, to fix the issues. Container crashing, something like that?

So the problem may be that this may be an error message people see when encountering some other error. i.e. you re-install and look at the logs and there this is. or was. 

This, of course, isn't about this particular bug, but rather to clear up what I see as the misunderstanding or miscommunication in this thread, which I suspect may be elsewhere too.

So it's always worthwhile to start a conversation, and if this situation is common around here, maybe it'd be useful to have a stock question, which you can copy paste, where you ask if it's broken or working, if people are just stressed about an error message or if the software doesn't start, crashes, or some such thing. 

Hope this helps!

**Comment by HernandoR** [comment] 2024-02-26 13:19
Just to clarify the issue:

There is a process during the startup to install/update calibre if the mod is identified.

During the process, I notice an curl log, that may ends inexpertly. And in that case, the /usr/bin/ebook-convert will not be created, but everything else would works fine.

Naturally, in such cases if one choose /apps/calibre/bin/ebook-convert, an error will show calling lib**.so missing( I don’t recall the precise name, but I have seen some related issue.)

发件人: Sveinbjörn Pálsson ***@***.***>
日期: 星期六, 2024年2月24日 21:26
收件人: linuxserver/docker-calibre-web ***@***.***>
抄送: Zhen Liu ***@***.***>, Comment ***@***.***>
主题: Re: [linuxserver/docker-calibre-web] [BUG] No such file or directory: 'xdg-icon-resource' (Issue #243)

Posting same issue, especially on one that is marked invalid for not having enough info in the issue description is extremely unhelpful.

I don't think people look at these logs unless something isn't working. Mostly.

The irony is that just marking it 'invalid' is also not enough info to go on.

I may have missed the bit where you said it was a harmless bug first time around, since this wasn't the case for me. Or so I recall. It's been a year so I'm not sure.

If I remember correctly, I was having issues with calibre (and calibre-web), and when seeing this error, I drew the obvious conclusion that this was the problem I needed to solve, to fix the issues. Container crashing, something like that?

So the problem may be that this may be an error message people see when encountering some other error. i.e. you re-install and look at the logs and there this is. or was.

This, of course, isn't about this particular bug, but rather to clear up what I see as the misunderstanding or miscommunication in this thread, which I suspect may be elsewhere too.

So it's always worthwhile to start a conversation, and if this situation is common around here, maybe it'd be useful to have a stock question, which you can copy paste, where you ask if it's broken or working, if people are just stressed about an error message or if the software doesn't start, crashes, or some such thing.

Hope this helps!
