### ISSUE TITLE
[BUG] Getting "no matching manifest for linux/arm/v8 in the manifest list entries" on aarch64 Raspberry Pi

### ISSUE THREAD

**Issue by permindersingh** [linuxserver/docker-calibre-web#280] opened 2023-11-09 21:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

pi@xxx.xxx.xx.xx: /calibre-web $ arch
aarch64
pi@xxx.xxx.xx.xx: /calibre-web $ uname -a
Linux xxx.xxx.xx.xx 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
pi@xxx.xxx.xx.xx: /calibre-web $ docker pull linuxserver/calibre-web
Using default tag: latest
latest: Pulling from linuxserver/calibre-web
no matching manifest for linux/arm/v8 in the manifest list entries
pi@xxx.xxx.xx.xx: /calibre-web $

### Expected Behavior

It should get installed

### Steps To Reproduce

Refer current behavior above

### Environment

```markdown
- OS:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- How docker service was installed:
curl -sSL https://get.docker.com | sh
sudo usermod -aG docker $USER
```

### CPU architecture

arm64

### Docker creation

```bash
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/pi/calibre-web/config:/config
      - /home/pi/calibre-web/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Container logs

```bash
Not applicable as container is not created
```

**Comment by aptalca** [comment] 2023-11-09 21:44
It means you have a 64 bit kernel but 32bit userspace

**Comment by permindersingh** [comment] 2023-11-09 21:47
@aptalca What should I do to install it then?

**Comment by thespad** [comment] 2023-11-09 22:06
You may be able to force it with the `arm64v8-latest` tag but either way the longer term solution is to install a proper 64-bit operating system.

**Comment by permindersingh** [comment] 2023-11-09 23:02
@thespad Thank you for the suggestion but can you give example?

**Comment by permindersingh** [comment] 2023-11-09 23:13
@thespad Following your direction this is how I updated the docker-compose.yml

version: "2.1"
services:
  calibre-web:
    image: registry.gitlab.com/linuxserver.io/docker-calibre-web/calibre-web:arm64v8-version-0.6.21
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/pi/calibre-web/config:/config
      - /srv/dev-disk-by-uuid-c84ec495-4cb7-42b2-941d-57b5937066a2/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

After running docker compose command, I got an error:
pi@pi: /calibre-web $ docker compose up -d
[+] Running 10/10
 ✔ calibre-web 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                      83.2s
   ✔ ed73b558eaa7 Pull complete                                                                                                                                                                                                  3.8s
   ✔ 07a0e16f7be1 Pull complete                                                                                                                                                                                                  0.6s
   ✔ 0042098b7449 Pull complete                                                                                                                                                                                                  0.6s
   ✔ 546628a3356b Pull complete                                                                                                                                                                                                  1.2s
   ✔ 4a78efec227f Pull complete                                                                                                                                                                                                  2.1s
   ✔ e1dc91c3af62 Pull complete                                                                                                                                                                                                  1.9s
   ✔ 2dc2cc02ca12 Pull complete                                                                                                                                                                                                 80.7s
   ✔ 36259f0a06e8 Pull complete                                                                                                                                                                                                  4.6s
   ✔ 4891b77803d7 Pull complete                                                                                                                                                                                                  5.2s
[+] Running 2/2
 ✔ Container calibre-web                                                                                                                                    Started                                                              1.2s
 ! calibre-web The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested                                                                      0.0s

**Comment by thespad** [comment] 2023-11-10 09:00
Yeah, it won't always work because it depends on the specific OS and hardware environment, not all mixed user/kernel space setups are the same.

In your case realistically your only option is to reinstall with a proper 64-bit OS. Be warned if you insist on sticking with Raspbian that they *still* default to offering 32-bit downloads.

**Comment by drizuid** [comment] 2023-11-19 00:09
potential work-around didn't work, the actual fix is provided. this is not a bug or anything we have control over, closing.

**Closed by drizuid** 2023-11-19 00:09 UTC
Labels: wontfix

**Comment by permindersingh** [comment] 2023-11-19 18:33
There is no fix for this provided. You can close the ticket if you want but the issue is still not resolved.

Best regards,
Perminder
________________________________

**Comment by Roxedus** [comment] 2023-11-19 18:34
There is nothing us to fix.

**Comment by permindersingh** [comment] 2023-11-19 18:37
Ok. Being disappointed, I will look for other alternatives. Thank you.

Best regards,
Perminder
________________________________

**Comment by thespad** [comment] 2023-11-19 18:44
Please read https://www.linuxserver.io/armhf, especially https://github.com/raspberrypi/linux/issues/5402

There's nothing we can do about this, Raspbian fucked up, and are continuing to fuck up.

**Comment by drizuid** [comment] 2023-11-19 21:11
> Ok. Being disappointed, I will look for other alternatives. Thank you. Best regards, Perminder

Only you can fix this, install a 64bit OS on your PI and things will work. We cannot do this for you.
