### ISSUE TITLE
DB Location is not Valid, Please Enter Correct Path

### ISSUE THREAD

**Issue by mabushey** [linuxserver/docker-calibre-web#104] opened 2020-10-16 01:10 UTC
Docker-compose with Traefik. There are numerous unresolved but closed issues on this, apparently no one can figure it out.

I enter `/books` in the box and it displays this error. My UID/GID is correctly set to 1000 and 1000.

**Comment by aptalca** [comment] 2020-10-16 01:50
You asked in another issue why one of our team members was `being hostile` and `randomly closing crap`. You're about to find out.

1. You did not fill out the issue template
2. You did not read the readme (it's explained in there)
3. This is not a bug, so you should seek help on discord or the forum as explained in the issue template

**Closed by aptalca** 2020-10-16 01:50 UTC

**Comment by mabushey** [comment] 2020-10-16 17:49
I was able to fix the problem by switching to the technosoft2000/calibre-web container. Normally I like linuxserver containers, but this one is broke.

**Comment by j0nnymoe** [comment] 2020-10-16 19:07
It's not but ok.

https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/calibre-web/latest/index.html

**Comment by krystofurr** [comment] 2020-10-24 23:55
I was having the same problem but realized that I was setting up my /books folder to an empty volume.  It has to be a valid pre-existing calibre database.  I did have one.  Just didn't point directly to it.  Maybe that's the issue.  Or try re-creating your calibre database from scratch.


_-v /books    |    Where your preexisting calibre database is locate._

**Comment by CHBMB** [comment] 2020-12-09 18:16
@mabushey If that is the extent of the information you provide nobody can help you.  You can be an ass about it all you want, but your n=1 report with absolutely none of the useful information we specifically request with the issue template helps nobody, least of all yourself. 

If that is me being hostile, then I make no apologies for that.  This is my spare time, it is too scarce and valuable right now to give any attention to reports like this.

**Comment by mabushey** [comment] 2020-12-09 23:00
I was able to get this container working. I didn't realize a requirement to run `docker-calibre-web` is to get `docker-calibre` running first.

**Comment by CHBMB** [comment] 2020-12-09 23:19
A requirement is to have an existing calibre database.

```
Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. It is also possible to integrate google drive and edit metadata and your calibre library through the app itself.
```

**Comment by alekc** [comment] 2021-01-27 14:45
@CHBMB if it's a hard requirement, then surely it should be mentioned in the Readme? I've double checked, and unless I am blind I cannot find any mention regarding the fact that the library db must me initialised. 

The application setup section `On the initial setup screen, enter /books as your calibre library location.` is not explicit in this aspect either. 

What would be good to have probably is a small section explaining that 
a) you need to have a preexisting library
b) how can you import it.

**Comment by aptalca** [comment] 2021-01-27 15:28
@alekc app description from the readme: 
```
Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.
```

It's not a requirement of our image. It's a requirement of the app itself.

**Comment by alekc** [comment] 2021-01-27 15:46
fair enough, I missed the `existing` word, but surely a small paragraph would not hurt right?

For example when I tried to run it, I didn't know about anything calibre-web app and I just assumed that it would permit me to replicate my workflow (take the book, convert it to mobi, ship to kindle via email) through the browser. It was totally unexpected the fact that I cannot simply just run the container and use it.

**Comment by decentral1se** [comment] 2021-11-30 12:12
`/usr/bin/calibredb restore_database --really-do-it --with-library /books`
