### ISSUE TITLE
link to instructions or readme on how to use this?

### ISSUE THREAD

**Issue by BretG137** [linuxserver/docker-calibre-web#147] opened 2021-06-12 21:44 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I don't know how calibre-web is intended to be used.  Following the instructions, I type /Books and it fails.  googling says that calibre-web is intended to be used with an existing calibre db.  I have the linuxserverio calibre container working fine but wanted to try calibre web because the webui looks nicer.  I see no obvious way to connect these containers and I can't find any instructions.  It would be nice if someone wrote something up or included a linked to some instructions.  Thanks!

------------------------------

**Comment by aptalca** [comment] 2021-06-12 21:51
You need to map the folder that contains your calibre db as `/books` as listed in the readme.

Closing as this is not a bug

**Closed by aptalca** 2021-06-12 21:51 UTC

**Comment by BretG137** [comment] 2021-06-12 22:00
> You need to map the folder that contains your calibre db as `/books` as listed in the readme.
> 
> 
> 
> Closing as this is not a bug

This is not helpful.  I have installed both linuxserver docker containers, there is no description of what a db is or how it should be mapped from one container to another.  Does calibre generate a db?  I don't see any mention of it anywhere, where is this generally store or mapped in the calibre docker container?  Is calibre intended to be installed on bare metal to use this container?  Also, I selected feature request not bug.  The request is: to include some sort of instructions on how this is to be used.

**Comment by aptalca** [comment] 2021-06-12 22:22
We can't really hold your hand through all the basic steps. Calibre database is a prerequisite of calibre-web, the upstream app. Calibre-web docs and website cover this. Our readme is not meant to teach one how to use the upstream app, but only how to set up the docker image. We expect you to have some knowledge of how the upstream app works and what it needs (or you can refer to their docs for that).

If you google `calibre database` you'll see tons of articles on what it is and where to find it.

Calibre-web docker image does not need the calibre docker image and the two need not be linked. Calibre-web just needs a calibre database, that's all. If you like, you can set up the calibre image once, let it create the database, then map that location to calibre-web.

With that said, these issues are for bugs (as described in the readme template). If you need help with setting things up, we have discord and discourse.

**Comment by BretG137** [comment] 2021-06-12 23:03
> We can't really hold your hand through all the basic steps. Calibre database is a prerequisite of calibre-web, the upstream app. Calibre-web docs and website cover this. Our readme is not meant to teach one how to use the upstream app, but only how to set up the docker image. We expect you to have some knowledge of how the upstream app works and what it needs (or you can refer to their docs for that).
> 
> 
> 
> If you google `calibre database` you'll see tons of articles on what it is and where to find it.
> 
> 
> 
> Calibre-web docker image does not need the calibre docker image and the two need not be linked. Calibre-web just needs a calibre database, that's all. If you like, you can set up the calibre image once, let it create the database, then map that location to calibre-web.
> 
> 
> 
> With that said, these issues are for bugs (as described in the readme template). If you need help with setting things up, we have discord and discourse.

I appreciate your reply.  It turns the installation was obvious and my problem was just a permission issue.  I still think the readme should just say: you need calibre to use this and /books needs to be the location of your metadata.db file.

**Comment by j0nnymoe** [comment] 2021-06-12 23:20
It already does
![image](https://user-images.githubusercontent.com/10374553/121791011-2db54f00-cbdd-11eb-90a9-b0d07a6c9764.png)
