### ISSUE TITLE
[BUG] <Metadata fetch function is still not working>

### ISSUE THREAD

**Issue by free521521521** [linuxserver/docker-calibre-web#225] opened 2022-12-16 06:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the update features include the Douban metadata fetching function, but in my case it still not working.
https://tinyurl.com/2mrlw6jn

### Steps To Reproduce

click a book
press "edit metadata"
press "fetch metadata"
press "search"

### Environment

```markdown
- OS:Docker
- How docker service was installed:
download image from Portainer, because the official one does not work.
```

### CPU architecture

x86-64

### Docker creation

```bash
Install by Docker in Synology without code.
```

### Container logs

```bash
Version | Details
7/31/22, 10:14 PM | Current version

Version | Details
7/31/22, 10:14 PM | Current version
```

**Comment by drizuid** [comment] 2022-12-27 16:42
Hello, thanks for opening this
A couple things
1) we do not support or recommend portainer for deploying our containers as it causes too many problems
2) we do not support or recommend using the synology ui to deploy containers as it causes too many problems
3) we do support the methods shown in our readmes (docker run and/or docker compose) and both work on synology.

Unfortunately, with the info you've provided and your use of unsupported methods, we are unable to reproduce this issue to help us troubleshoot. I will close this now, if you re-test using supported methods, please open a new issue and fully fill out the template. thank you!

**Closed by drizuid** 2022-12-27 16:42 UTC
Labels: invalid
